### Get address for logged-in user
GET http://localhost:3000/address
# Cookie: accessToken=

### Create new address
POST http://localhost:3000/address
# Cookie: accessToken=
Content-Type: application/json

{
  "address_firstname": "Conan",
  "address_lastname": "Edogawa",
  "address_phonenumber": "03-XXXX-XXXX",
  "address_address": "Mouri Detective Agency, 2nd Floor, Beika Building",
  "address_subdistrict": "Beika Town",
  "address_district": "Beika Ward",
  "address_province": "Tokyo",
  "address_postalcode": "152-0035"
}

### Update a note
PATCH http://localhost:3000/address/
# Cookie: accessToken=
Content-Type: application/json

{
  "address_firstname": "",
  "address_lastname": "",
  "address_phonenumber": "080-9876-5432",
  "address_address": "Mouri Detective Agency, 2nd Floor, Teito Building",
  "address_subdistrict": "",
  "address_district": "",
  "address_province": "",
  "address_postalcode": ""
}

### Delete a note
DELETE http://localhost:3000/address/
# Cookie: accessToken=