### Admin User Route - Get all users ✅
GET http://localhost:3030/users

### Admin User - Create a new user ❌
POST http://localhost:3030/users
Content-Type: application/json

{
  "user_name": "Joe",
  "user_lastname": "Joestar",

}

### User route - Signup a new user ✅
POST http://localhost:3030/auth/signup
Content-Type: application/json

{
  "user_name": "Gadme",
  "user_lastname": "isGadmin",
  "user_username": "Gadministrator",
  "user_email": "Gadme@example.com",
  "user_password": "123456789"
}

### User route - Login ✅
POST http://localhost:3030/auth/cookie/login
Content-Type: application/json

{
  "user_email": "Gadme@example.com",
  "user_password": "123456789"
}

### User route - Get User Profile ✅
GET http://localhost:3030/auth/profile
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGM1ODViYjBiNzNmNzA0ZTRhODcxOGUiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3NTc3NzU1NTYsImV4cCI6MTc1Nzc3OTE1Nn0.lVbMMVzRs7vOQinikpGhAAgEoQhiTD0BeDJD33MRXA8

### Test route - Verify the token (replace <TOKEN> with the token from the login response)
GET http://localhost:3030/auth/verify ✅
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGM1ODViYjBiNzNmNzA0ZTRhODcxOGUiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3NTc3NzU1NTYsImV4cCI6MTc1Nzc3OTE1Nn0.lVbMMVzRs7vOQinikpGhAAgEoQhiTD0BeDJD33MRXA8

### User route - Logout user ✅
POST http://localhost:3030/auth/logout